

version: '3.7'

services:
  web:
    container_name: django_web
    restart: unless-stopped
    build:
      context: .
    volumes:
      - static/:/static
      - media/:/media
      - ./:/app
    ports:
      - 8000:8000
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - my-network

volumes:
  # postgres_data:
  media:
  static:

networks:
  my-network:
