# Generated by Django 3.2.7 on 2023-01-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('biography', models.TextField()),
                ('photo', models.ImageField(upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('project_name', models.CharField(max_length=127)),
                ('pre_description', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Image')),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='PortfolioApp.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('pre_description', models.TextField()),
                ('descritipon', models.TextField()),
                ('image', models.ImageField(upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.project')),
            ],
        ),
    ]
