# Generated by Django 3.2.7 on 2023-02-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('biography', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('project_name', models.CharField(max_length=127)),
                ('pre_description', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Image')),
                ('link', models.URLField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='PortfolioApp.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('pre_description', models.TextField()),
                ('descritipon', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='Image')),
            ],
        ),
        migrations.CreateModel(
            name='SendGmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.aboutme')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='Image')),
                ('link', models.URLField()),
                ('name', models.CharField(max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.aboutme')),
            ],
        ),
    ]
