# Generated by Django 3.2.7 on 2023-02-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='project',
        ),
    ]
