# Generated by Django 3.2.7 on 2023-02-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0004_remove_aboutme_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='PortfolioApp.project'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.aboutme'),
        ),
    ]
