# Generated by Django 3.2.7 on 2023-01-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0004_alter_aboutme_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='user',
            field=models.TextField(),
        ),
    ]
