# Generated by Django 3.2.7 on 2023-02-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0005_auto_20230216_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='project',
        ),
    ]
