# Generated by Django 3.2.7 on 2023-02-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
