# Generated by Django 3.2.7 on 2023-01-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0007_auto_20230131_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendgmail',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
