# Generated by Django 3.2.7 on 2023-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0009_alter_sendgmail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendgmail',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
